// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE51lzifoGVLxib9b4HXrbOmNcZwY5tuk',
    appId: '1:751932178476:web:fcef527035e771c81f9189',
    messagingSenderId: '751932178476',
    projectId: 'grainhero-app',
    authDomain: 'grainhero-app.firebaseapp.com',
    storageBucket: 'grainhero-app.firebasestorage.app',
    measurementId: 'G-BYENFVVTZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSCZaFaxtT63gh5T7bfuf7Jpb_MnAz1QQ',
    appId: '1:751932178476:android:18304c942cd44b391f9189',
    messagingSenderId: '751932178476',
    projectId: 'grainhero-app',
    storageBucket: 'grainhero-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEHXN09HHzLnVMLw5c5CuJH0xwwNIyb0',
    appId: '1:751932178476:ios:2847f7438b515ce51f9189',
    messagingSenderId: '751932178476',
    projectId: 'grainhero-app',
    storageBucket: 'grainhero-app.firebasestorage.app',
    iosBundleId: 'com.example.grainheroTechnicianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEHXN09HHzLnVMLw5c5CuJH0xwwNIyb0',
    appId: '1:751932178476:ios:2847f7438b515ce51f9189',
    messagingSenderId: '751932178476',
    projectId: 'grainhero-app',
    storageBucket: 'grainhero-app.firebasestorage.app',
    iosBundleId: 'com.example.grainheroTechnicianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE51lzifoGVLxib9b4HXrbOmNcZwY5tuk',
    appId: '1:751932178476:web:4ea326c53240cd121f9189',
    messagingSenderId: '751932178476',
    projectId: 'grainhero-app',
    authDomain: 'grainhero-app.firebaseapp.com',
    storageBucket: 'grainhero-app.firebasestorage.app',
    measurementId: 'G-GED66X6Z88',
  );
}
